export const countries = [
  "Choose Your Country",
  "USA",
  "Canada",
  "United Kingdom",
  "UAE",
  "Australia",
  "Mexico",
  "Austria",
  "Belgium",
  "Caribbean Islands",
  "Colombia",
  "Denmark",
  "France",
  "Germany",
  "Ireland",
  "India",
  "Italy",
  "Luxembourg",
  "Malaysia",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Phillippines",
  "Poland",
  "Puerto Rico",
  "Singapore",
  "Saudi Arabia (Ships From Singapore)",
  "Spain",
  "Sweden",
  "Switzerland",
  "Other Countries",
];
